### PR TITLE
Add icefall RNN-T results

### PR DESCRIPTION
**Pull request by wgb14**
We would like to add results from Icefall RNN-T recipe. The numbers are comparable to those form Conformer CTC with ngram & attention rescoring, but decoding speed is much faster.
> it takes only 1 minute to decode the dev dataset

 https://github.com/k2-fsa/icefall/pull/318#issuecomment-1125625918

### CODE REVIEW

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/icefall/pull/361 has an updated version for the results of modified beam serach

`10.52/10.62` -> `10.50/10.60`

**Comment by chenguoguo** [comment]
Great, great, could you adjust the numbers, and rank it accordingly?

**Comment by wgb14** [comment]
Will do more decoding experiments and update results here

**Comment by csukuangfj** [comment]
> Will do more decoding experiments and update results here

You can also try `--iter xx --avg xx` instead of `--epoch xx --avg xx`.

**Comment by wgb14** [comment]
Update results here:
|         |  Dev  | Test  | 
|------|-------|-------|
| WER | 10.4 | 10.51 |

This RNN-T model outperforms other models.

**Review by dophist — APPROVED** [review]
@wgb14 Great

**Comment by chenguoguo** [comment]
Great, merging.

**Pull request merged**
