### PR TITLE
Add results from Icefall

### PR DESCRIPTION
**Pull request by wgb14**

### CODE REVIEW

**Review by dophist — COMMENTED** [review]
Guanbo, is it pure conformer CTC ? or with some sorts of ngram/attention rescorings ?

**Comment by wgb14** [comment]
> Guanbo, is it pure conformer CTC ? or with some sorts of ngram/attention rescorings ?

Decoding process is HLG decoding + n-gram LM rescoring + attention decoder rescoring

**Comment by wgb14** [comment]
I mentioned the decoding process in `RESULTS.md` in icefall. How do we reflect this process in leaderboard?

**Comment by dophist** [comment]
> 

use something like [conformer ctc + ngram & attention rescoring] as the link title should be fine, I think.

**Comment by wgb14** [comment]
> > 
> 
> use something like [conformer ctc + ngram & attention rescoring] as the link title should be fine, I think.

Fixed

**Review by dophist — APPROVED** [review]

**Comment by chenguoguo** [comment]
Can you move it to the top of the second half of the table since it gives the best results so far?

**Comment by wgb14** [comment]
> Can you move it to the top of the second half of the table since it gives the best results so far?

fixed

**Comment by chenguoguo** [comment]
Great, merging.

**Pull request merged**
